### ISSUE TITLE
Suggestion Initial Setup For Project

### ISSUE THREAD

**Issue by jigs1996** [cmshotel/hotelmanagement#2]
### After downloading project or anytime accessing project
![screenshot 120](https://user-images.githubusercontent.com/28808327/36044154-b91aef98-0df7-11e8-8259-af1f652086d8.png)

#### Give your suggestion

**Comment by jigs1996** [comment]
### why there is no update on this issue?

**Comment by utsavmori** [comment]
initial setup done [Check here](https://github.com/cmshotel/hotelmanagement/tree/dev1)

**Comment by jigs1996** [comment]
do not push your code anywhere..
just create a branch for new  module and push there so we have to manage only one repo
