### ISSUE TITLE
Suggest "Setting" Module

### ISSUE THREAD

**Issue by jigs1996** [cmshotel/hotelmanagement#3]
## <i><u>Structure</u></i>
<h3>Do not implement till @jigs1996 give permission to move ahed just discuss only </h3>
<ol>
<h3><li>General Setting</li></h3>
<ul>
<h4><li>site title</li></h4>
<h4><li>time zone</li></h4>
<h4><li>date format</li></h4>
<h4><li>time format</li></h4>
<h4><li>week start on</li></h4>
</ul>
<h3><li>Mail Server</li></h3>
<ul>
<h4><li>mail server</li></h4>
<h4><li>login name</li></h4>
<h4><li>pasword</li></h4>
<h4><li>ssl certificate</li></h4>
</ul>
<h3><li>DataBase</li></h3>
<br><br>
<b>Note:</b> here main bullet is menu name and sub-bullet is menu contains that settings

**Comment by utsavmori** [comment]
We can use mail server for proceeding feedback and complaints and mention the email content to different collections in database for easy tracking of complaints and feedback.all passwords should stored as hash.Admin password change is required after initial setup.

**Comment by jigs1996** [comment]
I asked for a suggestion. is there anything you can add it?.

**Comment by utsavmori** [comment]
In database we have to add changing of all common data like gst slabs and categories and plans.Edit booking is remaining.Cancel booking and refund status.Admin details change.

**Comment by jigs1996** [comment]
any progress on this issue???????? @Sunil1997 :question:
